### ISSUE TITLE
Another test issue (mine)

### ISSUE THREAD

**Issue by OndrejSpanel** [OpenGrabeso/cohubo#34]
**Some content** - so that we see the _Markdown_ response.

**Comment by stravissimo** [comment]
Ping the author.

**Comment by stravissimo** [comment]
Ping again.

**Comment by stravissimo** [comment]
This works like IM - huh. --- bing ho ho

**Comment by stravissimo** [comment]
Closed on the other end. Is it any different now?

**Comment by stravissimo** [comment]
No notification at all. :( At least nothing so far.

**Comment by OndrejSpanel** [comment]
It seems notifications are not immediate, they take some time, but them will come eventually (after a few minutes?)

Note: responding clears the notification.

**Comment by stravissimo** [comment]
Ping again from a puppet.

**Comment by stravissimo** [comment]
And again.

**Comment by stravissimo** [comment]
And again.

**Comment by stravissimo** [comment]
Once again.

**Comment by stravissimo** [comment]
A fresh comment by a puppet

**Comment by stravissimo** [comment]
A new comment from a puppet
