### ISSUE TITLE
Cannot see new comments

### ISSUE THREAD

**Issue by Bebul** [OpenGrabeso/cohubo#61]
I have issue with 5 comments, but last two are not shown in CoHubo

![image](https://user-images.githubusercontent.com/9265147/78779105-a8148e80-799c-11ea-9b90-718976a37ad9.png)

**Comment by Bebul** [comment]
I had to wait more, probably.
I can see it now.

**Comment by OndrejSpanel** [comment]
Cohubo is not loading new comments while open yet, a page refresh is needed for that.
